version: "3"

services:
  # This will be used in future by the Admin Data Persist API
  # admin-db:
  #   image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
  #   environment:
  #     POSTGRESQL_USER: ${POSTGRESQL_USER}
  #     POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
  #     POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
  #     POSTGRESQL_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
  #   ports:
  #     - ${POSTGRESQL_DATABASE_PORT}:5432
  #   networks:
  #     - agent-net
  #   volumes:
  #     - admin-db-data:/var/lib/pgsql/data

  wallet-db:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_WALLET_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_WALLET_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_WALLET_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_WALLET_ADMIN_PASSWORD}
    networks:
      - agent-net
    ports:
      - ${POSTGRESQL_WALLET_PORT}:5432
    volumes:
      - agent-wallet-db:/var/lib/pgsql/data

  aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.11-1_0.3.2
    ports:
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
      - ${AGENT_HTTP_PORT}:${AGENT_HTTP_PORT}
    networks:
      - agent-net
    depends_on:
      - wallet-db
    entrypoint: /bin/bash
    command:
      [
        "-c",
        "sleep 5;
        aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_HTTP_PORT} \
        --outbound-transport http \
        --endpoint ${AGENT_ENDPOINT} \
        --seed '${AGENT_SEED}' \
        --genesis-url '${LEDGER_BUILD_URL}' \
        --wallet-type 'indy' \
        --wallet-name '${WALLET_NAME}' \
        --wallet-key '${WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${WALLET_STORAGE_TYPE}' \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL_WALLET_HOST}:${POSTGRESQL_WALLET_PORT}\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_WALLET_USER}\",\"password\":\"${POSTGRESQL_WALLET_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_WALLET_ADMIN_USER}\",\"admin_password\":\"${POSTGRESQL_WALLET_ADMIN_PASSWORD}\"}' \
        --admin '0.0.0.0' ${AGENT_ADMIN_PORT} \
        --${ACAPY_ADMIN_MODE} \
        --label ${AGENT_NAME} \
        --auto-accept-invite \
        --auto-accept-requests \
        --auto-respond-messages \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-respond-presentation-proposal \
        --auto-respond-presentation-request \
        --timing \
        --log-level debug",
      ]
      # --seed '${AGENT_SEED}' \
  # agent-admin:
  #   image: dibbsza/didx-ng-admin:latest
  #   ports:
  #     - "${IP:-0.0.0.0}:20000:80"
  #   depends_on:
  #     - admin-db
  #   networks:
  #     - agent-net

networks:
  agent-net:

volumes:
  agent-wallet-db:
  # admin-db-data:
